DROP TABLE IF EXISTS delivery_trips CASCADE;
DROP TABLE IF EXISTS ingredients CASCADE;
DROP TABLE IF EXISTS product_mappings CASCADE;
DROP TABLE IF EXISTS recipe_mappings CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS shippers CASCADE;
DROP TABLE IF EXISTS trip_orders CASCADE;
DROP TABLE IF EXISTS view_history CASCADE;
