CREATE TABLE recipes (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL,
                         image_url TEXT,
                         cooking_steps TEXT,
                         ingredients TEXT,
                         tags VARCHAR(255)
);

CREATE TABLE recipe_products (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 recipe_id BIGINT NOT NULL,
                                 product_id BIGINT NOT NULL,

                                 CONSTRAINT uq_recipe_product UNIQUE (recipe_id, product_id),
                                 CONSTRAINT fk_recipe_products_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
                                 CONSTRAINT fk_recipe_products_product FOREIGN KEY (product_id) REFERENCES products(product_id) ON DELETE CASCADE
);

CREATE INDEX idx_recipe_products_product ON recipe_products(product_id);