-- V7: Thiết kế lại tính năng ảnh sản phẩm (từ một-một sang một-nhiều)

-- 1. Xóa cột image_url (đơn) cũ khỏi bảng products
-- (Chúng ta dùng IF EXISTS để script chạy an toàn dù đã chạy hay chưa)
ALTER TABLE products
DROP COLUMN IF EXISTS image_url;


-- 2. Tạo bảng product_images mới
CREATE TABLE product_images
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url      TEXT                                    NOT NULL, -- Dùng TEXT để lưu URL dài từ Cloudinary
    public_id      VARCHAR(255)                            NOT NULL, -- Dùng để xóa trên Cloudinary
    display_order  INT                                     NOT NULL DEFAULT 0, -- 0 là ảnh chính
    product_id     BIGINT                                  NOT NULL
);


-- 3. Thêm ràng buộc khóa ngoại (foreign key)
ALTER TABLE product_images
    ADD CONSTRAINT fk_product_images_on_product
        FOREIGN KEY (product_id)
            REFERENCES products (product_id)
            ON DELETE CASCADE; -- Quan trọng: Nếu xóa Product, tự động xóa tất cả Image liên quan


-- 4. Tạo index trên cột product_id để tối ưu truy vấn
CREATE INDEX idx_product_images_on_product_id
    ON product_images (product_id);